

export const VIEW_ALL_USER_REQUEST = "VIEW_ALL_USER_REQUEST";
export const VIEW_ALL_USER_SUCCESS = "VIEW_ALL_USER_SUCCESS";
export const VIEW_ALL_USER_FAILED = "VIEW_ALL_USER_FAILED";

// export const VIEW_SINGLE_USER_REQUEST = "VIEW_ALL_USER_REQUEST";